extends: airbnb-base
env:
  es6: true
  node: true
  mocha: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
globals:
  sails: true
  redisClient: true
  chance: true
  # services
  CommentService: true
  MovieService: true
  UtilityService: true
  # models
  Comment: true

rules:
  max-len:
    - 0
    - 200
    - 2
  no-console: error
  comma-dangle: ["error", {
    "arrays": "always-multiline",
    "objects": "always-multiline",
    "imports": "always-multiline",
    "exports": "always-multiline",
    "functions": "ignore"
  }]
  no-underscore-dangle: 0
  no-restricted-globals: 0
  func-names: 0
  camelcase: 0
  import/order: 0
  no-await-in-loop: 0