version: "2"
services:
  api:
    env_file:
      - ./docker-config/secrets.env
    container_name: paystack-wars
    restart: always
    build: .
    ports:
      - "1400:1400"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data: