version: "2"
services:
  web:
    container_name: paystack-wars
    restart: always
    build: .
    ports:
      - "1400:1400"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"